export const ACCESS_TOKEN_LOCAL_STORAGE_KEY = 'ACCESS_TOKEN';
export const ACCESS_TOKEN_EXPIRES_AT_LOCAL_STORAGE_KEY = 'ACCESS_TOKEN_EXPIRES_IN';

export const REFRESH_TOKEN_LOCAL_STORAGE_KEY = 'REFRESH_TOKEN';
export const REFRESH_TOKEN_EXPIRES_AT_LOCAL_STORAGE_KEY = 'REFRESH_TOKEN_EXPIRES_IN';
